version: 0.0.{build}
configuration: Release
services: mysql
before_build:
- ps: >-
    nuget restore

    $env:MYSQL_PWD="05200902"

    $cmd = '"C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "create database spslocal;" --user=root'

    iex "& $cmd"
build:
  verbosity: minimal
artifacts:
- path: CDatabase\bin\Release
  name: cdatabase_dll
deploy:
- provider: Local