version: 0.0.{build}
configuration: Release
services: mysql
before_build:
- ps: >-
    nuget restore

    $env:MYSQL_PWD="Password12!"

    $cmd = '"C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "create database spslocal;" --user=root'

    iex "& $cmd"
build:
  verbosity: minimal
artifacts:
- path: CDatabase\bin\Release
  name: cdatabase_dll_V$(appveyor_build_version)
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: cdatabase_dll_release_V$(appveyor_build_version)
  auth_token:
    secure: suCkyLyNzRHvwL46/CXjLdTJukroztvH+omv/KtZgW7cpoi8BhvAsgAwkEy1uBER
  artifact: CDatabase\bin\cdatabase_dll_release_V$(appveyor_build_version).zip
  draft: true
  prerelease: true
  force_update: true